# Profile section
profile:
  first_name: Adam
  last_name: Rohacs
  #picture: https://cdn.glitch.com/88028f3b-2a37-4207-9b84-e56ad97a9d3d%2Frodo_2021.png?v=1622471953248   # Hosted picture
  # picture: static/img/rodo_2021.png  # Local picture
  contact:
    address_one: Chicago, IL
    address_two:
    phone: 773-512-2903
  email: arohacs@gmail.com 
  description: |
    I am a DevOps Engineer/SRE with 9 years of experience designing, deploying, and optimizing on-prem and AWS cloud infrastructure.


# Social section
social:
  website:
  github: https://github.com/arohacs/
  twitter:
  linkedin: https://www.linkedin.com/in/adam-r-8958434
  facebook:
  dev: 
  medium:


# Experience section
experience:
  item7:
    position: Senior Site Reliability Engineer
    company: Cirium, a RELX Company
    from: December 2021
    to: Present
    description: 
      - I am an embedded SRE on a team dedicated to data processing and delivery of airline schedules. 
      - I maintain and improve AWS services with Infrastructure as Code (IaC) and DevOps practices,
      - create and maintain Terraform CI/CD pipelines on Gitlab CI to deploy infrastructure to AWS accounts.
      - I Migrated and modernized a CentOS and Ubuntu HPCC big data platform running on AWS EC2.
      - Reduced compression time by 84 percent by migrating from 7zip to pigz for a big data scripting platform.
      - Created ansible scripts and a docker image to automate a big data cluster and AWS server update
      - Optimized Windows FTP file delivery server infrastructure away from AWS EBS to the more cost effective S3.
      - Created scripts to simplify and automate CVE security remediation.
      - Improved observability by deploying a Datadog agent integrated with Pagerduty alerts via Terraform IaC
      - Migrated an AWS zip lambda to a docker container-based lambda to restore a development environment.
      - Create jenkins pipeline and scripts for validation and automated testing of AWS container-based lambdas.
      - Migrated TeamCity server and agents from on-prem to a container based AWS environment
      - Created and improved cross account IAM policies and roles; implemented AWS SSM to improve security

    
    link: https://www.cirium.com/
  item6:
    position: Community Leader
    company: Codeando México
    from: September 2019
    to: February 2021
    description: >
      Codeando México mainly focuses on executing activities that connect society and governments, the usage of technologies and internet-based solutions for civic purposes.
    link: http://codeandomexico.org/
  item5:
    position: Open Data Coordinator
    company: LAB León / General Direction of Innovation León
    from: July 2018
    to: September 2019
    description: >
      Pushing efforts to open (and work with) data in the city. Helping the city with trainings for digital jobs, including programming courses on Python and web development.
  item4:
    position: AI Consultant
    company: NULLSEC (Startup)
    from: July 2019
    to: September 2019
    description: >
      Working as an AI consultant for NULLSEC, a computer security company focused on ethical hacking. Particularly helping in the development of NullRansom, an analyzer-debugger software with the purpose of filtering TCP protocol requests, preventing preventively being targeted by malware and ransomware viruses.
    link: http://www.nullsec.site
  item3:
    position: Lead ML Engineer
    company: Omdena
    from: May 2019
    to: July 2019
    description: >
      Lead ML engineer in Omdena's collaborative tree identification challenge to prevent fire outbursts. Contributed with the models developed and the data preprocessing (we develped a Python package for it).
    link: https://medium.com/omdena/building-ai-for-good-by-the-people-for-the-people-d98ad78b5001
  item2:
    position: Jr. Python Software Developer
    company: CloudLinux
    from: February 2019
    to: May 2019
    description: >
      In charge of building automation solutions with Python. The tech stack used includes Scrapy, Luigi, requests, and MongoDB.
  item1:
    position: AI Research Assistant
    company: Research Center in Mathematics (CIMAT A.C.)
    from: February 2018
    to: February 2019
    description: >
      On charge of doing research and building neural networks for computer vision problems, focused on applications and solutions for real industry issues. Deployed trained models to production.
  reference: https://rodolfoferro.xyz/resume/


# Education section
education:
  item1:
    institution: University of Illinois at Chicago, Chicago, Illinois
    program: Bachelor of Psychology
    description: Major in Psychology, with classes in computer science
  item2:
    institution: Southern Illinois University, Carbondale, Illinois
    program: Psychology, Math, and Computer Science Courses


# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - markdown
  - git-alt
  - github
  - docker
  - google
  - slack
  - trello
  - apple
  - linux
  - terminal


extra_skills:
  - Python, Ruby, Bash, Powershell, HTML, XML, JSON, YAML, CSS, SQL
  - MySQL, PostgreSQL, MongoDB, Redis
  - AWS, experience with GCP, Azure SAML authentication/apps
  - Terraform, Chef, Puppet, Ansible, AWS Cloudformation
  - Docker, experience with Kubernetes
  - Datadog, New Relic, ELK, Grafana, Pagerduty
  - Jenkins, Spinnaker, Github actions, Gitlab CI, Teamcity, Bitbucket, AWS CodeDeploy
  - MacOS, Windows, Linux
